### PR TITLE
Migrate to null safety

### LINKED ISSUE #3: migration to null safety?
package isn't compatible with newest flutter version

### PR DESCRIPTION
**Pull request by prasadsunny1**
fixes #3

### CODE REVIEW

**Comment by prasadsunny1** [comment]
Please let me know how can this PR can be improved

**Comment by jakelumetta** [comment]
Thanks! @prasadsunny1   Requesting review from @deven98 

@mojomaze can you take a peek as well?

**Comment by d3xvn** [comment]
Just saw this, I will review by EOD

**Comment by prasadsunny1** [comment]
🔔

**Review by d3xvn — APPROVED** [review]
LGTM

**Comment by jakelumetta** [comment]
Thanks!

**Pull request merged**
